/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ktra1_1911505310114;

/**
 *
 * @author DELL
 */
public class home extends javax.swing.JFrame {
    public Student mStudentPanel;
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        DX_14 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        qlsv_14 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        qld_14 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Logout_14 = new javax.swing.JMenuItem();
        Exit_14 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        QLSV_14 = new javax.swing.JMenuItem();
        QLD_14 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        DX_14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ktra1_1911505310114/logout-icon-32.png"))); // NOI18N
        DX_14.setText("Đăng Xuất");
        DX_14.setFocusable(false);
        DX_14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DX_14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(DX_14);
        jToolBar1.add(jSeparator1);

        qlsv_14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ktra1_1911505310114/10207-man-student-light-skin-tone-icon-32.png"))); // NOI18N
        qlsv_14.setText("Quản lý sinh viên");
        qlsv_14.setFocusable(false);
        qlsv_14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        qlsv_14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(qlsv_14);
        jToolBar1.add(jSeparator2);

        qld_14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ktra1_1911505310114/gpa-icon-32.png"))); // NOI18N
        qld_14.setText("Quản lý điểm");
        qld_14.setFocusable(false);
        qld_14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        qld_14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(qld_14);
        jToolBar1.add(jSeparator3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ktra1_1911505310114/Actions-help-about-icon-32.png"))); // NOI18N
        jButton4.setText("Giới thiệu");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        jMenu1.setText("Hệ thống");

        Logout_14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ktra1_1911505310114/logout-icon-16.png"))); // NOI18N
        Logout_14.setText("Đăng xuất");
        jMenu1.add(Logout_14);

        Exit_14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ktra1_1911505310114/Button-Close-icon-16.png"))); // NOI18N
        Exit_14.setText("Thoát");
        jMenu1.add(Exit_14);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        QLSV_14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ktra1_1911505310114/10207-man-student-light-skin-tone-icon-16.png"))); // NOI18N
        QLSV_14.setText("Quản lý sinh viên");
        QLSV_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLSV_14ActionPerformed(evt);
            }
        });
        jMenu2.add(QLSV_14);

        QLD_14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ktra1_1911505310114/gpa-icon.png"))); // NOI18N
        QLD_14.setText("Quản lý điểm");
        jMenu2.add(QLD_14);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Trợ giúp");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ktra1_1911505310114/Actions-help-about-icon-16.png"))); // NOI18N
        jMenuItem5.setText("Nội Dung");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ktra1_1911505310114/Help-icon-16.png"))); // NOI18N
        jMenuItem6.setText("Giới thiệu");
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QLSV_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLSV_14ActionPerformed
        // TODO add your handling code here:
        mStudentPanel = newStudentPanel();
        ImageIcon icon = new ImageIcon(getClass().getResource("ktra1_1911505310114")) ;
    }//GEN-LAST:event_QLSV_14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DX_14;
    private javax.swing.JMenuItem Exit_14;
    private javax.swing.JMenuItem Logout_14;
    private javax.swing.JMenuItem QLD_14;
    private javax.swing.JMenuItem QLSV_14;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton qld_14;
    private javax.swing.JButton qlsv_14;
    // End of variables declaration//GEN-END:variables
}
